### PR TITLE
Added buildpack methods

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by geemus** [comment]
Thanks! Does this need a release as well?

**Comment by ransombriggs** [comment]
Let me check one thing before you release.

**Comment by ransombriggs** [comment]
@geemus I checked my one thing and it looks good (the node client auto-inserts a Range header which the buildpack url freaks out on, just wanted to make sure this did not have the same behavior)

**Comment by jkutner** [comment]
Yes, please release when you can. Thanks for testing @ransombriggs!

**Comment by geemus** [comment]
Released as part of 0.4.0

**Comment by dickeyxxx** [comment]
@jkutner do you need this as part of the toolbelt?

**Comment by jkutner** [comment]
@dickeyxxx no this was for heroku_hatchet and the buildpack tests: https://github.com/heroku/heroku-buildpack-ruby/pull/434

**Pull request merged**
